version: '3.1'
services:

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
